### ISSUE TITLE
question: how to get other text files to identify as text

### ISSUE THREAD

**Issue by tanj** [hangyav/textLSP#2]
I'm trying to get a reStructuredText document (extention `.rst`) to behave as text and be spell check, but I don't seem to get any checking done.

Is there a config for this or should any document type that isn't one that is known be processed as text?

**Comment by hangyav** [comment]
Yes, all unknown file types should be checked as plain text file. However, you need to set the `.rst` file type in your config to be checked. What text editor do you use and how does your config look like?

**Comment by tanj** [comment]
I'm using [helix](https://docs.helix-editor.com/master/)

I took the sample config from the README.md and converted to `toml`. I'm not sure where to add an extension to be included in checked files.

```toml
[[language]]
name = "rst"
language-servers = ["esbonio-lsp", "text-lsp"]
language-id = "restructuredtext"

# other config removed for clarity

[language-server.text-lsp]
command = "C:/Python310/Scripts/textlsp"

[language-server.text-lsp.config.analysers.languagetool]
enabled=true
check_text={on_open=true,on_save=true,on_change=false}

[language-server.text-lsp.config.analysers.gramformer]
enabled=false
gpu=false
check_text={on_open=false,on_save=true,on_change=false}

[language-server.text-lsp.config.analysers.hf_checker]
enabled=true
gpu=false
model='pszemraj/flan-t5-large-grammar-synthesis'
min_length=40
check_text={on_open=false,on_save=true,on_change=false}

[language-server.text-lsp.config.analysers.hf_completion]
enabled=true
gpu=false
model='bert-base-multilingual-cased'
topk=5

[language-server.text-lsp.config.analysers.documents]
org={ org_todo_keywords=['TODO','IN_PROGRESS','DONE']}
txt={parse=true}
```

**Comment by hangyav** [comment]
Your config looks good in general. The only issue is that in the config table you need to put everything (analysers and documents) under `textLSP`, e.g.: [language-server.text-lsp.config.**textLSP**.analysers.languagetool]. It works for me using helix version 23.05 and the following minimal config:

```toml
[[language]]
name = "rst"
language-server = { command="textlsp", language-id = "restructuredtext" }
config = {textLSP={analysers={languagetool={enabled=true,check_text={on_open=true, on_save=true,on_change=false}}}}}

```
